title: Rachel Chujie Zheng
position: Ph.D. Student
affiliation: University of Delaware
email: chz (at) udel.edu
keywords: Natural Language Processing / Machine Learning
google_scholar: https://scholar.google.com/citations?user=H7RziZgAAAAJ&hl=en
github_link: https://github.com/chz816
linkedin: https://www.linkedin.com/in/cjzheng/
avatar: ./assets/img/avatar.png
google_analytics: UA-163683932-1
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
