title: Rachel Chujie Zheng
position: Ph.D. Candidate
affiliation: University of Delaware
email: chz (at) udel.edu
keywords: Natural Language Processing / Machine Learning
google_scholar: https://scholar.google.com/citations?user=H7RziZgAAAAJ&hl=en
github_link: https://github.com/chz816
linkedin: https://www.linkedin.com/in/cjzheng/
avatar: ./assets/img/profile.png
google_analytics: UA-163683932-1
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: 3rd-year Ph.D. student in Natural Languege Processing
canonical: https://chz816.github.io
remote_theme: yaoyao-liu/minimal-light
